export const GET_CATALOG = 'app/GET_CATALOG'
export const ADD_ITEM_TO_SHOPPING_CART = 'app/ADD_ITEM_TO_SHOPPING_CART'
export const REMOVE_ITEM_FROM_SHOPPING_CART = 'app/REMOVE_ITEM_FROM_SHOPPING_CART'
